openapi: 3.0.0
info:
  title: Social app
  description: our first social app at LCO - Yash
  version: 1.0.1

servers:
  - url: http://localhost:4000/api/v1
    description: this is the local version of our app
  - url: http://localhost:4000/api/v1
    description: this one is just for demo